INSERT INTO APARTMENT_BLOCK VALUES(1,'BLOCK-1','Delhi');
INSERT INTO APARTMENT_BLOCK VALUES(2,'BLOCK-2','Delhi');
INSERT INTO APARTMENT_BLOCK VALUES(3,'BLOCK-3','Delhi');
INSERT INTO APARTMENT_BLOCK VALUES(4,'BLOCK-4','Delhi');
INSERT INTO APARTMENT_BLOCK VALUES(5,'BLOCK-5','Delhi');
INSERT INTO APARTMENT_BLOCK VALUES(6,'BLOCK-6','Delhi');
INSERT INTO APARTMENT_BLOCK VALUES(7,'BLOCK-7','Delhi');
INSERT INTO APARTMENT_BLOCK VALUES(8,'BLOCK-8','Delhi');
INSERT INTO APARTMENT_BLOCK VALUES(9,'BLOCK-9','Delhi');

